#!/usr/bin/env bash
# Report generator: produces markdown reports with actionable recommendations

set -euo pipefail

# Generate a full markdown report from analysis JSON
generate_report() {
    local analysis="$1"
    local report_file="$2"

    local timestamp
    timestamp=$(date '+%Y-%m-%d %H:%M:%S %Z')
    local report_id
    report_id=$(date '+%Y%m%d_%H%M%S')

    log_info "Generating report: $report_file"

    {
        # Header
        echo "# ELK Log Analysis Report"
        echo ""
        echo "**Generated:** $timestamp"
        echo "**Report ID:** $report_id"
        echo "**Endpoint:** ${ELK_ENDPOINT}"
        echo "**Index:** ${ELK_INDEX}"
        echo "**Time Range:** Last ${ELK_TIME_RANGE}"
        echo "**Log Level Filter:** ${ELK_LOG_LEVEL}"
        echo ""

        # Executive Summary
        generate_summary "$analysis"

        # Severity Assessment
        generate_severity_assessment "$analysis"

        # Error Categories
        generate_categories_section "$analysis"

        # Top Error Messages
        generate_top_errors "$analysis"

        # Pattern Detection
        generate_patterns_section "$analysis"

        # Service Breakdown
        generate_services_section "$analysis"

        # Timeline
        generate_timeline_section "$analysis"

        # Recommendations
        generate_recommendations "$analysis"

        # Next Steps Checklist
        generate_next_steps "$analysis"

        echo ""
        echo "---"
        echo "*Report generated by ELK Log Analysis Agent*"

    } > "$report_file"

    log_info "Report written to $report_file"
}

generate_summary() {
    local analysis="$1"

    echo "## Executive Summary"
    echo ""

    local total fatal errors warnings services hosts
    total=$(echo "$analysis" | jq -r '.summary.total_entries')
    fatal=$(echo "$analysis" | jq -r '.summary.fatal')
    errors=$(echo "$analysis" | jq -r '.summary.errors')
    warnings=$(echo "$analysis" | jq -r '.summary.warnings')
    services=$(echo "$analysis" | jq -r '.summary.unique_services')
    hosts=$(echo "$analysis" | jq -r '.summary.unique_hosts')

    echo "| Metric | Count |"
    echo "|--------|-------|"
    echo "| Total Log Entries | $total |"
    echo "| Fatal/Critical | $fatal |"
    echo "| Errors | $errors |"
    echo "| Warnings | $warnings |"
    echo "| Affected Services | $services |"
    echo "| Affected Hosts | $hosts |"
    echo ""

    if [[ "$fatal" -gt 0 ]]; then
        echo "> **ALERT:** $fatal fatal/critical entries detected. Immediate attention required."
        echo ""
    fi
}

generate_severity_assessment() {
    local analysis="$1"

    echo "## Severity Assessment"
    echo ""

    local fatal errors patterns_high
    fatal=$(echo "$analysis" | jq -r '.summary.fatal')
    errors=$(echo "$analysis" | jq -r '.summary.errors')
    patterns_high=$(echo "$analysis" | jq '[.patterns[] | select(.severity == "high")] | length')

    local severity="LOW"
    local description=""

    if [[ "$fatal" -gt 0 ]]; then
        severity="CRITICAL"
        description="Fatal errors detected. Services may be down or data loss may be occurring."
    elif [[ "$errors" -gt 50 || "$patterns_high" -gt 2 ]]; then
        severity="HIGH"
        description="High volume of errors with concerning patterns. Degraded service likely."
    elif [[ "$errors" -gt 10 ]]; then
        severity="MEDIUM"
        description="Moderate error volume. Monitor closely for escalation."
    else
        description="Low error volume. Routine monitoring sufficient."
    fi

    echo "**Overall Severity: $severity**"
    echo ""
    echo "$description"
    echo ""
}

generate_categories_section() {
    local analysis="$1"

    local cat_count
    cat_count=$(echo "$analysis" | jq '.categories | length')

    if [[ "$cat_count" -eq 0 ]]; then
        return
    fi

    echo "## Error Categories"
    echo ""
    echo "| Category | Count | Severity |"
    echo "|----------|-------|----------|"

    echo "$analysis" | jq -r '.categories[] | "| \(.category) | \(.count) | \(.severity) |"'
    echo ""
}

generate_top_errors() {
    local analysis="$1"

    local msg_count
    msg_count=$(echo "$analysis" | jq '.top_messages | length')

    if [[ "$msg_count" -eq 0 ]]; then
        return
    fi

    echo "## Top Error Messages"
    echo ""

    echo "$analysis" | jq -r '.top_messages[] | "**\(.count)x** — `\(.message[:150])`\n"'
    echo ""
}

generate_patterns_section() {
    local analysis="$1"

    local pattern_count
    pattern_count=$(echo "$analysis" | jq '.patterns | length')

    if [[ "$pattern_count" -eq 0 ]]; then
        echo "## Pattern Detection"
        echo ""
        echo "No significant patterns detected."
        echo ""
        return
    fi

    echo "## Pattern Detection"
    echo ""

    echo "$analysis" | jq -r '.patterns[] |
        "### \(.type | gsub("_"; " ") | ascii_upcase)\n\n" +
        "- **Severity:** \(.severity)\n" +
        "- **Description:** \(.description)\n" +
        (if .count then "- **Occurrences:** \(.count)\n" else "" end) +
        (if .affected_services then "- **Affected Services:** \(.affected_services | join(", "))\n" else "" end) +
        (if .detail then "- **Detail:** \(.detail)\n" else "" end) +
        ""'
    echo ""
}

generate_services_section() {
    local analysis="$1"

    local svc_count
    svc_count=$(echo "$analysis" | jq '.services | length')

    if [[ "$svc_count" -eq 0 ]]; then
        return
    fi

    echo "## Service Breakdown"
    echo ""
    echo "| Service | Error Count | First Seen | Last Seen |"
    echo "|---------|-------------|------------|-----------|"

    echo "$analysis" | jq -r '.services[] | "| \(.service) | \(.count) | \(.first_seen // "N/A") | \(.last_seen // "N/A") |"'
    echo ""
}

generate_timeline_section() {
    local analysis="$1"

    local tl_count
    tl_count=$(echo "$analysis" | jq '.timeline | length')

    if [[ "$tl_count" -eq 0 ]]; then
        return
    fi

    echo "## Error Timeline (by hour)"
    echo ""
    echo "| Time Window | Count | Visual |"
    echo "|-------------|-------|--------|"

    local max_count
    max_count=$(echo "$analysis" | jq '[.timeline[].count] | max')

    echo "$analysis" | jq -r --argjson max "$max_count" '
        .timeline[] |
        "| \(.hour) | \(.count) | \("█" * ((.count * 20 / $max) | floor | if . < 1 then 1 else . end)) |"
    '
    echo ""
}

# The core value: actionable recommendations based on detected issues
generate_recommendations() {
    local analysis="$1"

    echo "## Recommendations"
    echo ""

    local rec_num=1
    local categories
    categories=$(echo "$analysis" | jq -r '.categories[].category')

    # Connection/Network recommendations
    if echo "$categories" | grep -q "Connection/Network"; then
        echo "### $rec_num. Network Connectivity Issues"
        echo ""
        echo "- **Verify target service availability** — Check if downstream services are running and reachable"
        echo "- **Review DNS resolution** — Ensure DNS entries are correct and TTLs are appropriate"
        echo "- **Check network policies/firewalls** — Verify security groups, network policies, and firewall rules allow traffic"
        echo "- **Increase connection timeouts** — If timeouts are too aggressive, increase them with backoff"
        echo "- **Implement circuit breakers** — Prevent cascading failures with circuit breaker patterns (e.g., Hystrix, resilience4j)"
        echo "- **Add retry logic with exponential backoff** — Transient network issues often resolve with retries"
        echo ""
        rec_num=$((rec_num + 1))
    fi

    # Memory recommendations
    if echo "$categories" | grep -q "Memory"; then
        echo "### $rec_num. Memory Issues"
        echo ""
        echo "- **Increase memory limits** — Review container/pod memory limits and increase if under-provisioned"
        echo "- **Profile memory usage** — Use profiling tools (jmap, pprof, node --inspect) to identify leaks"
        echo "- **Review GC settings** — Tune garbage collection parameters for your runtime"
        echo "- **Check for memory leaks** — Look for unclosed connections, growing caches, or event listener accumulation"
        echo "- **Implement memory-aware caching** — Use bounded caches with eviction policies (LRU, TTL)"
        echo ""
        rec_num=$((rec_num + 1))
    fi

    # Disk/Storage recommendations
    if echo "$categories" | grep -q "Disk/Storage"; then
        echo "### $rec_num. Disk/Storage Issues"
        echo ""
        echo "- **Free disk space** — Remove old logs, temp files, and unused artifacts"
        echo "- **Increase volume size** — Expand persistent volumes or EBS volumes"
        echo "- **Implement log rotation** — Ensure log rotation is configured to prevent disk exhaustion"
        echo "- **Review storage quotas** — Check and adjust disk quotas for the affected services"
        echo "- **Set up disk usage alerts** — Alert at 80% capacity to prevent outages"
        echo ""
        rec_num=$((rec_num + 1))
    fi

    # Auth recommendations
    if echo "$categories" | grep -q "Auth"; then
        echo "### $rec_num. Authentication/Authorization Issues"
        echo ""
        echo "- **Rotate credentials** — Check if API keys, tokens, or certificates have expired"
        echo "- **Verify service account permissions** — Ensure service accounts have required RBAC roles"
        echo "- **Check token expiration** — Review JWT/OAuth token TTLs and refresh mechanisms"
        echo "- **Audit access policies** — Review IAM policies, Kubernetes RBAC, or application-level permissions"
        echo "- **Implement token refresh** — Add automatic token refresh before expiration"
        echo ""
        rec_num=$((rec_num + 1))
    fi

    # Database recommendations
    if echo "$categories" | grep -q "Database"; then
        echo "### $rec_num. Database Issues"
        echo ""
        echo "- **Check connection pool settings** — Ensure pool size matches workload (min/max connections)"
        echo "- **Review slow queries** — Identify and optimize queries causing timeouts or deadlocks"
        echo "- **Check database health** — Verify replication lag, disk space, and CPU on database servers"
        echo "- **Review schema migrations** — Ensure recent migrations completed successfully"
        echo "- **Implement connection retry** — Add retry logic for transient database connection failures"
        echo "- **Consider read replicas** — Offload read traffic if the primary is overloaded"
        echo ""
        rec_num=$((rec_num + 1))
    fi

    # HTTP 5xx recommendations
    if echo "$categories" | grep -q "HTTP 5xx"; then
        echo "### $rec_num. HTTP 5xx Server Errors"
        echo ""
        echo "- **Check application logs** — Review stack traces for the root cause of 500 errors"
        echo "- **Verify upstream dependencies** — 502/503 errors often indicate upstream service issues"
        echo "- **Review recent deployments** — Check if errors correlate with a recent code or config change"
        echo "- **Scale horizontally** — If 503s indicate overload, add more instances"
        echo "- **Implement health checks** — Ensure load balancers route traffic only to healthy instances"
        echo ""
        rec_num=$((rec_num + 1))
    fi

    # Application errors
    if echo "$categories" | grep -q "Application"; then
        echo "### $rec_num. Application Runtime Errors"
        echo ""
        echo "- **Review stack traces** — Identify the exact code path causing exceptions"
        echo "- **Check for null/undefined handling** — Add defensive null checks where needed"
        echo "- **Review recent code changes** — Correlate errors with recent commits or deployments"
        echo "- **Add input validation** — Ensure all external inputs are validated before processing"
        echo "- **Improve error handling** — Add try/catch blocks and graceful degradation"
        echo ""
        rec_num=$((rec_num + 1))
    fi

    # Configuration errors
    if echo "$categories" | grep -q "Configuration"; then
        echo "### $rec_num. Configuration Issues"
        echo ""
        echo "- **Verify environment variables** — Check that all required env vars are set in the deployment"
        echo "- **Review ConfigMaps/Secrets** — Ensure Kubernetes ConfigMaps and Secrets are up to date"
        echo "- **Check config file syntax** — Validate YAML/JSON/TOML configuration files"
        echo "- **Compare environments** — Diff configuration between working and broken environments"
        echo ""
        rec_num=$((rec_num + 1))
    fi

    # Resource limit recommendations
    if echo "$categories" | grep -q "Resource Limits"; then
        echo "### $rec_num. Resource Limit Issues"
        echo ""
        echo "- **Review rate limits** — Check if API rate limits need adjustment"
        echo "- **Implement request throttling** — Add client-side rate limiting to stay within quotas"
        echo "- **Scale resources** — Increase CPU/memory limits if hitting resource ceilings"
        echo "- **Add caching** — Cache frequently accessed data to reduce API calls"
        echo "- **Implement backpressure** — Use queue-based processing to handle load spikes"
        echo ""
        rec_num=$((rec_num + 1))
    fi

    # Pattern-based recommendations
    local has_burst has_repeated has_cross_service
    has_burst=$(echo "$analysis" | jq '[.patterns[] | select(.type == "error_burst")] | length')
    has_repeated=$(echo "$analysis" | jq '[.patterns[] | select(.type == "repeated_error")] | length')
    has_cross_service=$(echo "$analysis" | jq '[.patterns[] | select(.type == "cross_service_failure")] | length')

    if [[ "$has_burst" -gt 0 ]]; then
        echo "### $rec_num. Error Burst Detected"
        echo ""
        echo "- **Investigate trigger event** — Check for deployments, config changes, or external events at burst start time"
        echo "- **Review auto-scaling** — Ensure auto-scaling responds quickly enough to load spikes"
        echo "- **Implement circuit breakers** — Prevent error cascades during burst periods"
        echo ""
        rec_num=$((rec_num + 1))
    fi

    if [[ "$has_cross_service" -gt 0 ]]; then
        echo "### $rec_num. Cross-Service Failure Pattern"
        echo ""
        echo "- **Identify the root service** — Determine which service failed first (check timestamps)"
        echo "- **Review service dependencies** — Map the dependency graph to understand cascade paths"
        echo "- **Implement bulkheads** — Isolate service failures to prevent propagation"
        echo "- **Add fallback mechanisms** — Implement graceful degradation when dependencies fail"
        echo ""
        rec_num=$((rec_num + 1))
    fi

    # General recommendations (always included)
    echo "### $rec_num. General Recommendations"
    echo ""
    echo "- **Set up alerting** — Configure alerts for error rate thresholds in your monitoring system"
    echo "- **Implement structured logging** — Use consistent log formats with correlation IDs for tracing"
    echo "- **Review SLOs** — Check if current error rates violate Service Level Objectives"
    echo "- **Schedule post-mortem** — If this is a significant incident, schedule a blameless post-mortem"
    echo ""
}

generate_next_steps() {
    local analysis="$1"

    echo "## Next Steps Checklist"
    echo ""

    local fatal
    fatal=$(echo "$analysis" | jq -r '.summary.fatal')
    local errors
    errors=$(echo "$analysis" | jq -r '.summary.errors')

    echo "- [ ] Review this report with the on-call team"

    if [[ "$fatal" -gt 0 ]]; then
        echo "- [ ] **URGENT:** Investigate and resolve fatal/critical errors immediately"
        echo "- [ ] Verify affected services are operational"
        echo "- [ ] Notify stakeholders of potential impact"
    fi

    if [[ "$errors" -gt 20 ]]; then
        echo "- [ ] Triage top error messages and assign owners"
    fi

    echo "- [ ] Implement fixes for the highest-severity categories"
    echo "- [ ] Re-run this analysis after fixes to verify resolution"
    echo "- [ ] Update monitoring/alerting based on findings"
    echo "- [ ] Document root cause and resolution in incident tracker"
    echo ""
}

# Print report summary to stdout (for CLI output)
print_report_summary() {
    local analysis="$1"

    echo ""
    echo "=========================================="
    echo "  ELK LOG ANALYSIS - SUMMARY"
    echo "=========================================="
    echo ""

    local total fatal errors warnings services
    total=$(echo "$analysis" | jq -r '.summary.total_entries')
    fatal=$(echo "$analysis" | jq -r '.summary.fatal')
    errors=$(echo "$analysis" | jq -r '.summary.errors')
    warnings=$(echo "$analysis" | jq -r '.summary.warnings')
    services=$(echo "$analysis" | jq -r '.summary.unique_services')

    printf "  Total Entries:     %s\n" "$total"
    printf "  Fatal/Critical:    %s\n" "$fatal"
    printf "  Errors:            %s\n" "$errors"
    printf "  Warnings:          %s\n" "$warnings"
    printf "  Affected Services: %s\n" "$services"
    echo ""

    local cat_count
    cat_count=$(echo "$analysis" | jq '.categories | length')
    if [[ "$cat_count" -gt 0 ]]; then
        echo "  Error Categories:"
        echo "$analysis" | jq -r '.categories[] | "    [\(.severity | ascii_upcase)] \(.category): \(.count)"'
        echo ""
    fi

    local pattern_count
    pattern_count=$(echo "$analysis" | jq '.patterns | length')
    if [[ "$pattern_count" -gt 0 ]]; then
        echo "  Detected Patterns:"
        echo "$analysis" | jq -r '.patterns[] | "    [\(.severity | ascii_upcase)] \(.type): \(.description[:80])"'
        echo ""
    fi

    echo "=========================================="
}
